require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  # Solid Cache를 개발 환경에서도 사용하여 캐싱 테스트
  config.cache_store = :solid_cache_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  
  # Bullet configuration for N+1 query detection
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = false  # 브라우저 팝업 비활성화
    Bullet.bullet_logger = true  # log/bullet.log 파일에 기록
    Bullet.console = true  # 콘솔에 출력
    Bullet.rails_logger = true  # Rails 로그에 기록
    Bullet.add_footer = true  # 페이지 하단에 정보 추가
    
    # Ignore false positives
    Bullet.add_safelist type: :unused_eager_loading, class_name: "ApprovalLine", association: :approval_line_steps
    Bullet.add_safelist type: :unused_eager_loading, class_name: "ApprovalRequest", association: :approval_histories
    Bullet.add_safelist type: :unused_eager_loading, class_name: "ApprovalRequest", association: :approval_line
    Bullet.add_safelist type: :unused_eager_loading, class_name: "ApprovalLineStep", association: :approver
    Bullet.add_safelist type: :unused_eager_loading, class_name: "ExpenseCode", association: :expense_code_approval_rules
  end
end
